RecipeWeekly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('main.urls')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),

    # url(r'^', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns 
#     # urlpatterns += patterns('', 

    #     (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
    # )

main/urls.py
from django.conf.urls import url, include 
from django.contrib.auth import views as auth_views

from .views import recipes, users, api 


urlpatterns = [
	url(r'^$', recipes.home, name='home'),
	url(r'^about/$', recipes.about, name='about'),
	url(r'^recipes/$', recipes.RecipeList.as_view(), name='recipe_list'),
	url(r'^recipes/(?P<pk>[0-9]+)$', recipes.RecipeDetail.as_view(), name='recipe_detail'),
	url(r'^ingredients/$', recipes.IngredientList.as_view(), name='ingredient_list'),
	url(r'^ingredients/(?P<pk>[0-9]+)$', recipes.IngredientDetail.as_view(), name='ingredient_detail'),
	url(r'^create/$', recipes.RecipeCreate.as_view(), name='create_recipe'),
	# url(r'^create/$', recipes.create_recipe, name='create_recipe'),

	url(r'^search/$', recipes.Search.as_view(), name='search'),


	# Users
	url(r'^users/$', users.UserList.as_view(), name='user_list'),
	url(r'^users/(?P<slug>\w+)$', users.UserDetail.as_view(), name='user_detail'),
	url(r'^register/$', users.UserRegistrationView.as_view(), name='user_registration'),
	url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
	url(r'^logout/$', users.logout_user, name='logout'),
	url(r'^delete_user/$', users.delete_user, name='delete_user'),

	url(r'^profile/$', users.update_profile, name='update_profile'),
	url(r'^profile/password/$', users.change_password, name='change_password'),

	url(r'^save_recipe/$', users.add_to_user_saved_recipes, name='save_recipe'),


	# API urls
	url(r'^api/$', api.Root.as_view()),
	url(r'^api/recipes/$', api.RecipeList.as_view()),
	# url(r'^api/recipes/create/$', api.RecipeCreate.as_view()),
	url(r'^api/recipes/save/$', api.SaveRecipe.as_view()),
	url(r'^api/recipes/like/$', api.LikeRecipe.as_view()),
	url(r'^api/recipes/dislike/$', api.DislikeRecipe.as_view()),
	url(r'^api/recipes/(?P<pk>[0-9]+)$', api.RecipeDetail.as_view()),
	url(r'^api/users/$', api.UserList.as_view(), name='api_users_list'),
	url(r'^api/users/(?P<pk>[0-9]+)$', api.UserDetail.as_view()),

	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

# url(r'^(?P<recipe_id>[0-9]+)/$', views.detail, name='detail'), 
# access captured group () in view method through self.args[0] or self.kwargs

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver 
from django.utils import timezone 


import logging
logger = logging.getLogger('main')


class Ingredient(models.Model):
	raw_name 	= models.CharField(max_length=200) # Lowercase and hyphens in between words
	name 		= models.CharField(max_length=200) # Capitalized and with spaces

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.raw_name.replace('-', ' ').title()
		return super(Ingredient, self).save(*args, **kwargs)


# Encompasses recipes from external API source, as well as user uploaded
class Recipe(models.Model):
	name	 		= models.CharField(max_length=300) 
	creator 		= models.ForeignKey('Profile', related_name='created_recipes', null=True, blank=True)
	is_yummly_recipe = models.BooleanField(default=False)
	is_user_recipe	= models.BooleanField(default=False)
	ingredient_list	= models.TextField() # String representation
	ingredients 	= models.ManyToManyField(Ingredient) # Foreign key model representation
	instructions	= models.TextField()
	photo			= models.ImageField(upload_to='recipe_photos/', null=True, blank=True)

	# Machine learning algorithm to determine similar recipes
	related_recipes	= models.ManyToManyField('self', blank=True)

	# Data included in Yummly API
	yummly_url	 	= models.CharField(max_length=300, blank=True) 
	yummly_source 	= models.CharField(max_length=300, blank=True) 
	yummly_rating	= models.IntegerField(default=0, blank=True)
	yummly_time_in_seconds	= models.IntegerField(default=0, blank=True) 
	yummly_image_url = models.CharField(max_length=300, blank=True)

	# Taste profile from Yummly
	bitter			= models.FloatField(blank=True, default=0)
	meaty			= models.FloatField(blank=True, default=0)
	salty			= models.FloatField(blank=True, default=0)
	sour			= models.FloatField(blank=True, default=0)
	sweet			= models.FloatField(blank=True, default=0)
	piquant			= models.FloatField(blank=True, default=0)

	# Timestamps
	date_created	= models.DateTimeField(editable=False)
	date_modified	= models.DateTimeField(editable=False)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.__update_timestamps()
		return super(Recipe, self).save(*args, **kwargs)

	def __update_timestamps(self):
		if not self.id: # Being created
			self.date_created = timezone.now()
		self.date_modified = timezone.now()

	def _post_save_link_ingredients(self):
		for ingredient_name in self.ingredient_list.split(' '):
			try:
				ingredient = Ingredient.objects.get(raw_name=ingredient_name)
			except Ingredient.DoesNotExist:
				ingredient = Ingredient.objects.create(raw_name=ingredient_name)

			if ingredient not in self.ingredients.all():
				self.ingredients.add(ingredient)

	def num_saves(self):
		count = self.profiles_saved.all().count()
		return count

@receiver(post_save, sender=Recipe)
def recipe_saved(sender, instance, created, **kwargs):
	instance._post_save_link_ingredients()


# Each user has a profile with additional information
class Profile(models.Model):
	user 			= models.OneToOneField(User, on_delete=models.CASCADE)
	bio 			= models.TextField(max_length=500, blank=True)
	saved_recipes 	= models.ManyToManyField(Recipe, related_name='profiles_saved', blank=True)
	
	# voted_recipes	= models.ManyToManyField(Recipe, through='RecipeVote', related_name='profiles_voted')
	liked_recipes	= models.ManyToManyField(Recipe, related_name='profiles_liked', blank=True)
	disliked_recipes = models.ManyToManyField(Recipe, related_name='profiles_disliked', blank=True)

	date_created 	= models.DateTimeField(auto_now_add=True) 
	date_modified 	= models.DateTimeField(auto_now=True) 


	def __str__(self):
		return self.user.username + "'s profile"


	# def liked_recipes(self):
	# 	liked_recipes = self.voted_recipes.filter(recipevote__liked=True)
	# 	return liked_recipes

	# def disliked_recipes(self):
	# 	disliked_recipes = self.voted_recipes.filter(recipevote__liked=False)
	# 	return disliked_recipes



# Listeners to keep user profile in sync with its corresponding user
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	profile = instance.profile 
	# profile.liked_recipes = profile.voted_recipes.filter(recipevote__liked=True)
	# profile.disliked_recipes = profile.voted_recipes.filter(recipevote__liked=False)
	profile.save() 



# Keeps track of like and dislike of a user for a recipe
class RecipeVote(models.Model):
	user_profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	recipe 		= models.ForeignKey(Recipe, on_delete=models.CASCADE)

	liked 		= models.NullBooleanField(default=None)
	# disliked	= models.NullBooleanField()

	date_modified = models.DateTimeField(auto_now=True)


	def __str__(self):
		if self.liked == True: 		s = " likes "
		elif self.liked == False: 	s = " dislikes "
		else: 						s = " neutral to "

		return str(self.user_profile) + s + str(self.recipe)

main/forms.py
from django.contrib.auth.models import User
from django import forms 
from django.contrib.auth.forms import UserCreationForm 

from .models import Profile, Recipe 


class RecipeCreateForm(forms.ModelForm):
	# ingredient_list	= forms.CharField(widget=forms.HiddenInput)
	instructions 	= forms.CharField(widget=forms.Textarea)
	photo 			= forms.ImageField(label="Select a photo", help_text="Help text")

	class Meta:
		model = Recipe 
		fields = ['name', 'ingredient_list', 'instructions', 'photo']




class UserForm(forms.ModelForm):
 	password = forms.CharField(widget=forms.PasswordInput)

 	class Meta:
 		model = User 
 		fields = ['username', 'email', 'password']


class UserRegistrationForm(UserCreationForm):
	# email = forms.CharField(required=True)

	class Meta:
		model = User
		fields = ['username'] # password already include twice for confirmation

	def save(self, commit=True):
		user = super(UserRegistrationForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		# user.email = self.cleaned_data['email']
		user.username = self.cleaned_data['username']

		if commit:
			user.save()
		return user 


class UserInfoForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')

class ProfileInfoForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('bio',)

main/views/api.py
import json
#from urllib.request import Request as url_request
#import facebook # Facebook API sdk
import logging
logger = logging.getLogger('main')

# Django 
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView, View
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, AdminPasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.backends import ModelBackend
from django.contrib import messages 
from django.conf import settings
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

# Django extensions
from social_django.models import UserSocialAuth
from rest_framework.views import APIView
from rest_framework.response import Response 
from rest_framework import status 
from rest_framework import generics
from rest_framework import permissions 
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse as api_reverse

# Local
from main.models import Recipe, Ingredient
from main.forms import UserForm, UserRegistrationForm, UserInfoForm, ProfileInfoForm
from main.serializers import RecipeSerializer, RecipeDetailSerializer, UserSerializer, UserDetailSerializer, RecipeCreateSerializer



############################################################
# API Views
############################################################

class Root(APIView):
	def get(self, request, format=None):
		return Response({
			'users': api_reverse('api_users_list', request=request, format=format),
			# Include all API endpoint urls
		})

class RecipeList(generics.ListAPIView):
	queryset = Recipe.objects.all()
	serializer_class = RecipeSerializer

class RecipeCreate(generics.CreateAPIView):
	queryset = Recipe.objects.all()
	serializer_class = RecipeCreateSerializer
	permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

	def perform_create(self, serializer):
		serializer.save(creator=self.request.user, is_user_recipe=True)

class RecipeDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = Recipe.objects.all()
	serializer_class = RecipeDetailSerializer 

class UserList(generics.ListAPIView):
	queryset = User.objects.all()
	serializer_class = UserSerializer

class UserDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = User.objects.all()
	serializer_class = UserDetailSerializer 


class SaveRecipe(APIView):
	permission_classes = (permissions.IsAuthenticated,)

	def post(self, request, format=None):
		recipe_id = request.data['recipe_id']
		recipe = Recipe.objects.get(pk=recipe_id)
		profile = request.user.profile
		if recipe in profile.saved_recipes.all(): 
			profile.saved_recipes.remove(recipe) # If already liked, remove from liked
		else:
			profile.saved_recipes.add(recipe) # Otherwise add to liked
		return Response({ 'status': "Processed save request on user '{}' for recipe '{}'".format(request.user, recipe) })


class LikeRecipe(APIView):
	permission_classes = (permissions.IsAuthenticated,)

	def post(self, request, format=None):
		recipe_id = request.data['recipe_id']
		recipe = Recipe.objects.get(pk=recipe_id)
		profile = request.user.profile
		if recipe in profile.liked_recipes.all(): 
			profile.liked_recipes.remove(recipe) # If already liked, remove from liked
		else:
			profile.liked_recipes.add(recipe) # Otherwise add to liked
		if recipe in profile.disliked_recipes.all(): # If in disliked, remove
			profile.disliked_recipes.remove(recipe)
		return Response({ 'status': "Processed like request on user '{}' for recipe '{}'".format(request.user, recipe) })


class DislikeRecipe(APIView):
	permission_classes = (permissions.IsAuthenticated,)

	def post(self, request, format=None):
		recipe_id = request.data['recipe_id']
		recipe = Recipe.objects.get(pk=recipe_id)
		profile = request.user.profile
		if recipe in profile.disliked_recipes.all(): 
			profile.disliked_recipes.remove(recipe) # If already liked, remove from liked
		else:
			profile.disliked_recipes.add(recipe) # Otherwise add to liked
		if recipe in profile.liked_recipes.all(): # If in disliked, remove
			profile.liked_recipes.remove(recipe)
		return Response({ 'status': "Processed dislike request on user '{}' for recipe '{}'".format(request.user, recipe) })

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}
<div class="container">    
  <h1>About</h1>

  <div class="row about-cards">

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Browser Makes Request</h3>
        </div>
        <div class="panel-body">
          The user enters a url address into their browser, such as <code>https://recipy.com/recipes/</code>.
          Browser -> Internet Provider -> Hosting Server
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Server Receives Request</h3>
        </div>
        <div class="panel-body">
          The files for the website all exist on the server, and sends back the file specified by the request. 
          In this case, our server is running the Django Python web framework. 
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">URL Mapping</h3>
        </div>
        <div class="panel-body">
          The first thing Django does is look at the url and map it to a view, which handles the request logic. 
          <code>url(r'^recipes/$', recipes.RecipeList.as_view(), name='recipe_list')</code>

        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">View</h3>
        </div>
        <div class="panel-body">
          This view does three things: link it with the Recipe model, determine the html template to be rendered, and return a set of recipes.
          <pre>
class RecipeList(ListView):
  model = Recipe
  template_name = 'main/recipe_list.html'

  # Recipe models to pass to template
  def get_queryset(self):
    return Recipe.objects.order_by('name')[:20]
          </pre>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Model</h3>
        </div>
        <div class="panel-body">
          The Recipe model is a Python class that simplifies storage in a SQL database. 
          <pre>
class Recipe(models.Model):
  name      = models.CharField(max_length=200) 
          </pre>

          It also can correspond directly to other models in the database.
          <pre>
  ingredients   = models.ManyToManyField(Ingredient) 
          </pre>

        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Template</h3>
        </div>
        <div class="panel-body">
          This is where the HTML is created that can be sent to the browser and interacted with. 
        </div>
      </div>
    </div>


  </div>
</div>

{% endblock content %}

main/templates/main/base.html
{% load static %}
{% load myfilters %} {# Doesn't load for extended templates #}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Recommendation System</title>

  <link rel="shortcut icon" type="image/png" href="{% static 'main/images/ReciPy Logo 2.png' %}"/>


  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Bootstrap CSS - Default -->
  {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> #}

  <!-- Bootstrap CSS - Bootswatch Sandstone theme -->
  <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">

	<!-- Bootstrap JS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!-- Jasny Bootstrap CSS -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

  <!-- Jasny Bootstrap JS -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

  <!-- D3.js -->
  <!--<script src="https://d3js.org/d3.v4.min.js"></script>-->

  <!-- Font Awesome icons -->
  <script src="https://use.fontawesome.com/a7115d7118.js"></script>

  <!-- Highlight.js -->
  <!--<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>-->



  <!-- My CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">

  <!-- My JavaScript -->
  <script src="{% static 'main/js/script.js' %}"></script>

  <!-- Include CSRF token for all pages -->
  <script> 
    window.CSRF_TOKEN = "{{ csrf_token }}"; 
    window.USER_IS_LOGGED_IN = {% if user.is_authenticated %} true {% else %} false {% endif %};
    window.CURRENT_PAGE = "{{ request.path }}";
  </script>

</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#base-navbar-collapse" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'main/images/ReciPy Logo 2.png' %}" class="img-responsive">
        </a>
        <a class="navbar-brand" href="{% url 'home' %}">
          <span>Recommendation System</span>
        </a>
	    </div>

	    <div class="collapse navbar-collapse" id="base-navbar-collapse">
        {% with request.resolver_match.url_name as current_page %}
	      <ul class="nav navbar-nav">
	        <li class="{% if current_page == 'recipe_list' %} active {% endif %}"><a href="{% url 'recipe_list' %}">Recipes</a></li>
          <li class="{% if current_page == 'ingredient_list' %} active {% endif %}"><a href="{% url 'ingredient_list' %}">Ingredients</a></li>
          <li class="{% if current_page == 'user_list' %} active {% endif %}"><a href="{% url 'user_list' %}">Users</a></li>
          <li class="{% if current_page == 'create_recipe' %} active {% endif %}"><a href="{% url 'create_recipe' %}">Add Recipe</a></li>
          <li class="{% if current_page == 'about' %} active {% endif %}"><a href="{% url 'about' %}">About</a></li>
	      </ul>
        {% endwith %}

        <form action="{% url 'search' %}" method="get" class="navbar-form navbar-left">
          <div class="form-group">
            <input name="q" id="id_q" type="text" class="form-control" placeholder="Search recipes, users" autocomplete="off" value="{{ query_string }}">
          </div>
          <button type="submit" class="btn btn-default btn-search"><i class="fa fa-search"></i></button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_active %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'update_profile' %}">Profile</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </li>
          {% else %}
            <li class="{% if current_page == 'user_registration' %} active {% endif %}"><a href="{% url 'user_registration' %}">Register</a></li>
            <li class="{% if current_page == 'login' %} active {% endif %}"><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
	    
 			</div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

  <div class="container">
    {% include 'messages_template.html' %}
  </div>

	{% block content %}
		<h1>Put content here</h1>
	{% endblock content %}

</body>
</html>

main/templates/main/ingredient_detail.html
{% extends "main/base.html" %}

{% block content %}

	<div class="container">

		<h1>{{ ingredient.name }}</h1>

		<p>Recipes:
			<ul>
			{% for recipe in ingredient.recipe_set.all %}
				<li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a></li>
			{% endfor %}
			</ul>
		</p>
	</div>

{% endblock content %}

main/templates/main/ingredient_list.html
{% extends "main/base.html" %}

{% block content %}

	<div class="container">

		<h1>Ingredients <span class="text-muted">({{ ingredient_list.count }} total)</span></h1>
		{% if ingredient_list %}
			<ul class="list-group">
			{% for ingredient in ingredient_list %}
				<li class="list-group-item">
          <i class="fa fa-apple" aria-hidden="true"></i>
					<a href="{% url 'ingredient_detail' ingredient.id %}">{{ ingredient.name }}</a>
					({{ ingredient.recipe_set.count }} recipes)
				</li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No ingredients listed.</p>
		{% endif %}

	</div>

{% endblock content %}

main/templates/main/user_recipe_create.html
{% extends 'main/base.html' %}
{% load myfilters %}


{% block content %}
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h1 class="panel-title">Create New Recipe</h1>
        </div>
        <div class="panel-body">

          <form id="create-recipe-form" class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <!-- Recipe Name -->
            <div class="form-group">
              <label class="control-label col-md-2" for="id_name">Recipe Name</label>
              <div class="col-md-4">
                <input name="name" id="id_name" type="text" class="form-control" required autofocus>
              </div> 
              {% if form.name.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.name.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>

            <!-- Ingredients -->
            <div class="form-group">
              <label class="control-label col-md-2" for="id_currentIngredient">Ingredients</label>
              <div class="col-md-3 col-xs-9">
                <input name="currentIngredient" type="text" id="id_currentIngredient" class="form-control">
                <input name="ingredient_list" type="text" id="id_ingredient_list" class="form-control hidden">
              </div> 
              <div class="col-md-1 col-xs-3">
                <button id="addIngredientsButton" type="button" class="btn btn-info" tabindex="-1">Add</button>
              </div>
              {% if form.ingredient_list.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.ingredient_list.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <div class="col-md-offset-2 col-md-3 col-xs-9">
                <ul id="ingredient-list-group" class="list-group"></ul>
              </div>
            </div>

            <!-- Instructions -->
            <div class="form-group">
              <label class="control-label col-md-2" for="id_instructions">Instructions</label>
              <div class="col-md-8">
                <textarea name="instructions" id="id_instructions" type="textarea" class="form-control" rows="6" placeholder="Explain how to make your recipe." form="create-recipe-form" required></textarea>
              </div> 
              {% if form.instructions.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.instructions.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>

            <!-- Picture -->
            <div class="form-group">
              <label class="control-label col-md-2">Photo</label>
              <div class="col-md-4">
                <!--<label class="btn btn-info btn-file" for="id_photo">
                  Upload Photo <input name="photo" type="file" id="id_photo" style="display: none;" required>
                </label>-->
                <div class="fileinput fileinput-new" data-provides="fileinput">
                  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                  <div>
                    <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
                      <input name="photo" type="file" id="id_photo" required>
                    </span>
                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                  </div>
                </div>                
              </div> 
              {% if form.photo.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.photo.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>



            <!-- Submit button -->
            <div class="form-group">
              <div class="col-md-offset-2 col-md-4">
                <button type="submit" class="btn btn-primary btn-block">Create</button>
              </div>
            </div>

          </form>

          {# {{ form.as_p }} #}


      </div>
    </div>
  </div>

</div>
{% endblock %}